# include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    document_ignores: ignore
    avoid_catches_without_on_clauses: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    literal_only_boolean_expressions: false
    avoid_positional_boolean_parameters: false